name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm
    - uses: actions/setup-node@v2
      with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - run: npm ci
    - run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
