name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm
    - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - run: npm install
    - run: npm run deploy
